server:
  port: 8090
spring:
  application:
    name: MSS-User-Auth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mss_auth
    username: root
    password: root
#  security:
#    user:
#      name: miracle
#      password: Miracle@1
#      roles: user
jwt:
  secret: miraclesoft
